# ==============================================
# Forge Foundary Configuration (v1.0)
# ==============================================

modes_path: Modes # Absolute path OR Relative to the tool
mode: laravel-ddd